# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

# conda, mac, simg
variables:
    NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-sv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
    NF_PROCESS_FILES: "modules/local/wf-human-sv.nf"
    NF_IGNORE_PROCESSES: "getAllChromosomesBed,minimap2_ubam"
    NF_WORKFLOW_OPTS: "--sv --bam demo_data/test.bam --ref demo_data/chr20_human_g1k_v37_part.fasta.gz --bed demo_data/target.bed --tr_bed demo_data/human_hs37d5.trf.bed"
    CI_FLAVOUR: "new"
    PYTEST_CONTAINER_CONFIG_KEY: "e2l_base_tag"

conda-run:
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude: [] # give me everything pal

docker-run:
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude:
            - ${CI_PROJECT_NAME}/**/*.bam
            - ${CI_PROJECT_NAME}/**/*.cram
            - ${CI_PROJECT_NAME}/**/*.fa
            - ${CI_PROJECT_NAME}/**/*.fna
            - ${CI_PROJECT_NAME}/**/*.fasta
            - ${CI_PROJECT_NAME}/**/ref_cache/**

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "wf-human-snp_modelint",
                "wf-human-snp_modelext",
                "wf-human-snp_covblock",
                "wf-human-sv",
                "wf-human-str",
                "wf-human-cnv",
                "gzref-ucram-methyl",
                "gzref-bam-methyl-hap",
                "omni"
              ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never

        - if: $MATRIX_NAME == "wf-human-snp_modelint"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,phase_contig_haplotag,merge_haplotagged_contigs,get_genome,get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--snp --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac_prom --phase_vcf --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "wf-human-snp_modelext"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,lookup_clair3_model,phase_contig_haplotag,merge_haplotagged_contigs,get_genome,get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--snp --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phase_vcf --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "wf-human-snp_covblock"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,lookup_clair3_model,phase_contig_haplotag,merge_haplotagged_contigs,\
                                    get_genome,aggregate_all_variants,aggregate_full_align_variants,aggregate_pileup_variants,create_candidates,\
                                    evaluate_candidates,get_qual_filter,makeReport,make_chunks,merge_pileup_and_full_vars,output_snp,phase_contig,\
                                    pileup_variants,post_clair_phase_contig,select_het_snps,vcfStats"
              NF_WORKFLOW_OPTS: "--snp --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phase_vcf --bam_min_coverage 100"

        - if: $MATRIX_NAME == "wf-human-sv"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-sv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf"
              NF_IGNORE_PROCESSES: "getAllChromosomesBed,minimap2_ubam,get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--sv --bam demo_data/test.bam --ref demo_data/chr20_human_g1k_v37_part.fasta.gz --bed demo_data/target.bed --tr_bed demo_data/human_hs37d5.trf.bed --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "wf-human-cnv"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-cnv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-cnv.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--cnv --bam demo_data/test.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz --bin_size 500 --bam_min_coverage 0.00001"
        
        - if: $MATRIX_NAME == "gzref-ucram-methyl"
          variables:
              NF_BEFORE_SCRIPT: "wget -q -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-methyl/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf modules/local/common.nf"
              NF_IGNORE_PROCESSES: "index_ref_gzi,mapula,get_genome,get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--methyl --bam demo_data/demo.ucram --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 --ubam_bam2fq_threads 1 --bam_min_coverage 0.00001"

        - if: $MATRIX_NAME == "gzref-bam-methyl-hap"
          variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-str/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf modules/local/common.nf"
              NF_IGNORE_PROCESSES: "minimap2_ubam,index_ref_gzi,mapula,get_genome,get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--methyl --bam demo_data/demo.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 --ubam_bam2fq_threads 1 --bam_min_coverage 0.00001 --phase_methyl"

        - if: $MATRIX_NAME == "wf-human-str"
          variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-str/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-str.nf"
              NF_IGNORE_PROCESSES: "get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--str --bam demo_data/demo.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name demo --sex female --bam_min_coverage 0.00001"


        #TODO tr_bed in test data
        - if: ($MATRIX_NAME == "omni" && $CI_COMMIT_BRANCH == "dev-omni")
          variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/demo_data.tar.gz && tar -xzvf demo_data.tar.gz && cat demo_data/VERSION && rm demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,post_clair_phase_contig,getAllChromosomesBed,minimap2_ubam,get_coverage,getVersions,getParams,failedQCReport"
              NF_WORKFLOW_OPTS: "--snp --sv --methyl --bam demo_data/demo.bam --ref demo_data/demo.fasta --bed demo_data/demo.bed --clair3_model_path demo_data/ont_r104_e81_sup_g5015 --sample_name OMNI --bam_min_coverage 0.00001"
