# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

# conda, mac, simg
variables:
    NF_BEFORE_SCRIPT: "wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-sv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
    NF_PROCESS_FILES: "modules/local/wf-human-sv.nf"
    NF_IGNORE_PROCESSES: "getAllChromosomesBed,minimap2_ubam"
    NF_WORKFLOW_OPTS: "--sv --bam demo_data/test.bam --ref demo_data/chr20_human_g1k_v37_part.fasta.gz --bed demo_data/target.bed --tr_bed demo_data/human_hs37d5.trf.bed"
    CI_FLAVOUR: "new"
    PYTEST_CONTAINER_CONFIG_KEY: "e2l_base_tag"

conda-run:
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude: [] # give me everything pal

docker-run:
    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "wf-human-snp_modelint",
                "wf-human-snp_modelext",
                "wf-human-sv",
                "wf-human-cnv",
                "gzref-ubam-methyl",
                "omni"
              ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never

        - if: $MATRIX_NAME == "wf-human-snp_modelint"
          variables:
              NF_BEFORE_SCRIPT: "wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap"
              NF_WORKFLOW_OPTS: "--snp --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac_prom --phase_vcf"

        - if: $MATRIX_NAME == "wf-human-snp_modelext"
          variables:
              NF_BEFORE_SCRIPT: "wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/snp_demo.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,lookup_clair3_model"
              NF_WORKFLOW_OPTS: "--snp --bam snp_demo/chr6_chr20.bam --bed snp_demo/chr6_chr20.bed --ref snp_demo/chr6_chr20.fasta --clair3_model_path snp_demo/ont_r104_e81_sup_g5015 --phase_vcf"

        - if: $MATRIX_NAME == "wf-human-sv"
          variables:
              NF_BEFORE_SCRIPT: "wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-sv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf"
              NF_IGNORE_PROCESSES: "getAllChromosomesBed,minimap2_ubam"
              NF_WORKFLOW_OPTS: "--sv --bam demo_data/test.bam --ref demo_data/chr20_human_g1k_v37_part.fasta.gz --bed demo_data/target.bed --tr_bed demo_data/human_hs37d5.trf.bed"

        - if: $MATRIX_NAME == "wf-human-cnv"
          variables:
              NF_BEFORE_SCRIPT: "wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-cnv/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-cnv.nf"
              NF_IGNORE_PROCESSES: ""
              NF_WORKFLOW_OPTS: "--cnv --bam demo_data/test.bam --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz --bin_size 500"
        
        - if: $MATRIX_NAME == "gzref-ubam-methyl"
          variables:
              NF_BEFORE_SCRIPT: "wget -O demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-methyl/demo_data.tar.gz && tar -xzvf demo_data.tar.gz"
              NF_PROCESS_FILES: "workflows/methyl.nf"
              NF_IGNORE_PROCESSES: ""
              NF_WORKFLOW_OPTS: "--methyl --bam demo_data/demo.cram --ref demo_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.gz --sample_name HOOT --ubam_map_threads 2 --ubam_sort_threads 1 --ubam_bam2fq_threads 1"


        #TODO tr_bed in test data
        - if: ($MATRIX_NAME == "omni" && $CI_COMMIT_BRANCH == "dev-omni")
          variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-human-variation/demo_data.tar.gz && tar -xzvf demo_data.tar.gz && cat demo_data/VERSION && rm demo_data.tar.gz"
              NF_PROCESS_FILES: "modules/local/wf-human-sv.nf modules/local/wf-human-snp.nf"
              NF_IGNORE_PROCESSES: "hap,post_clair_phase_contig,getAllChromosomesBed,minimap2_ubam"
              NF_WORKFLOW_OPTS: "--snp --sv --methyl --bam demo_data/demo.bam --ref demo_data/demo.fasta --bed demo_data/demo.bed --clair3_model_path demo_data/ont_r104_e81_sup_g5015 --sample_name OMNI"
