name: epi2melabs-nf-human-variation-common
channels:
    - conda-forge
    - epi2melabs
    - bioconda
dependencies:
    - aplanat==0.6.5
    - fastcat==0.4.11
    - epi2melabs==0.0.22
    - mosdepth==0.3.3
    - samtools>=1.15
    - perl-digest-md5
    - gzip
