name: epi2melabs-wf-human-sv
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.6.5
    - fastcat>=0.4.11
    - samtools >=1.8
    - minimap2==2.24
    - sniffles=2.0.3
    - Truvari==3.5.0
    - bcftools==1.15.1 # filterCalls
    - vcflib==1.0.3 # sortVcf
