name: epi2melabs-nf-human-snp
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.9.*
    - aplanat==0.6.5
    - bcftools>=1.10.2
    - clair3==0.1.12
    - fastcat>=0.4.11
    - epi2melabs==0.0.22
